image: node:9.2.0

clone:
  depth: full

pipelines:
  default:
    - step:
        script:
          - npm install
          - npm test
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
